apiVersion: v1
kind: Service
metadata:
    name: tfm-frontend
spec:
    ports:
    - port: 80
      targetPort: 4100
    selector:
      app: tfm-frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-frontend
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: tfm-frontend
          servicePort: 80
