apiVersion: v1
kind: Service
metadata:
    name: tfm-backend
spec:
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
    selector:
      app: tfm-backend
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: tfm-backend
          servicePort: 3000